-- LeadScout — seed.
--
-- Antes aquí havia datos de ejemplo (business_profiles, leads, messages...).
-- Se han retirado a propósito: describían un esquema que la aplicación no usa
-- (ver supabase/migrations/20260928000100_leadscout_app_schema.sql) y sus
-- usuarios apuntaban a auth.users, así que `supabase db reset` fallaba.
--
-- Los datos de prueba se generan solos: `POST /api/scan` guarda la búsqueda y
-- sus leads, y `POST /api/auth/signup` crea el usuario.
--
-- Este archivo se ejecuta en `supabase db reset` (ver [db.seed] en config.toml).
-- Si algún día quieres datos de ejemplo, inserta usuarios REALES de auth
-- (signup por la API o por el panel) y deja que la app rellene el resto.
select 1;
